[package]
name = "analyticsdb-engine"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
arrow-flight.workspace = true
async-trait.workspace = true
bytes.workspace = true
analyticsdb-core = { path = "../analyticsdb-core" }
analyticsdb-control = { path = "../analyticsdb-control" }
chrono.workspace = true
datafusion.workspace = true
datafusion-common.workspace = true
datafusion-execution.workspace = true
datafusion-functions-aggregate.workspace = true
datafusion-physical-expr.workspace = true
datafusion-physical-plan.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlparser.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tonic.workspace = true
tracing.workspace = true
uuid.workspace = true
object_store.workspace = true
regex = "1.12.3"
tokio-stream.workspace = true
num_cpus.workspace = true
dashmap.workspace = true
bincode.workspace = true
async-stream.workspace = true

[dev-dependencies]
rcgen = { workspace = true }
time = { workspace = true }
criterion = { workspace = true }
analyticsdb-control = { path = "../analyticsdb-control" }
datafusion = { workspace = true }

[[bench]]
name = "index_lookup_bench"
harness = false

[[bench]]
name = "planner_bench"
harness = false

[[bench]]
name = "query_log_bench"
harness = false
