[package]
name = "analyticsdb-engine"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
analyticsdb-core = { path = "../analyticsdb-core" }
analyticsdb-control = { path = "../analyticsdb-control" }
chrono.workspace = true
datafusion.workspace = true
datafusion-common.workspace = true
datafusion-physical-expr.workspace = true
datafusion-physical-plan.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlparser.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
